[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions/"

[functions.ogp]
  external_node_modules = ["canvas"]
  included_files = ["functions/font.ttf"]
